// <auto-generated />
namespace PodcastFeedGenerator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class channel_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(channel_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201711051625518_channel_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
